### ISSUE TITLE
Fact "docker": undefined method []' for nil:NilClass on RHEL-8(docker-podman)

### ISSUE THREAD

**Issue by dusharu** [puppetlabs/puppetlabs-docker#749]
## Describe the Bug
Error in facter when use podman-docker.rpm on RHEL-8
```
puppet agent -t

Info: Using configured environment 'develop'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom fact "docker": undefined method `[]' for nil:NilClass  #<--- this ERROR
Info: Caching catalog for prod-bis-mmisc1.scartel.dc
Info: Applying configuration version '1621517818'
Notice: Applied catalog in 8.78 seconds

```

## Expected Behavior
Add support for podman to /opt/puppetlabs/puppet/cache/lib/facter/docker.rb

```
/opt/puppetlabs/puppet/bin/facter  --custom-dir /opt/puppetlabs/puppet/cache/lib/facter/ docker

# Expected - json with docker info
# in fact -  nothing
```

## Steps to Reproduce
install podman-docker.noarch from repo os-rhel8-appstream
run `puppet agent -t`
or run `/opt/puppetlabs/puppet/bin/facter  --custom-dir /opt/puppetlabs/puppet/cache/lib/facter/ -d docker`

## Environment
- OS: Red Hat Enterprise Linux release 8.3 (Ootpa)
- puppet: 5.5.22
- podman version 2.2.1
- facter: 3.11.14 (commit 2f05c0b208c0848bc0052ac7abf772754f4b79da)

## Additional Context

**Comment by cswarren** [comment]
I'm also having this error show up on Centos 7 systems that don't have docker installed.

**Comment by silug** [comment]
This appears to have been fixed with #773.

**Comment by makewhatis** [comment]
This was broken in a different way for us when going from  C7 to C8, 773 did not fix. Looks like in the `network inspect` json output, podman returns a key for "id" in lowercase, and docker returns "Id", pascal case. 

This is where I had to change it, fwiw. I'm sure there is a better way of doing this...so I'm just leaving this for anyone that hits this.  

```diff --git a/docker/lib/facter/docker.rb b/docker/lib/facter/docker.rb
index b7cb379b54..d3a674b0c6 100644
--- a/docker/lib/facter/docker.rb
+++ b/docker/lib/facter/docker.rb
@@ -92,7 +92,12 @@ Facter.add(:docker) do
           docker_network_names.each do |network|
             inspect = JSON.parse(Facter::Util::Resolution.exec("#{docker_command} network inspect #{network}"))
             docker['network'][network] = inspect[0]
-            network_id = docker['network'][network]['Id'][0..11]
+            # support docker and podman. Podman outputs lowercase id
+            if docker['network'][network].key?('id')
+              network_id = docker['network'][network]['id'][0..11]
+            else
+              network_id = docker['network'][network]['Id'][0..11]
+            end
```
